[build]
  # no build step for pure static site
  command = ""
  # folder with your index.html
  publish = "public"

[build.environment]
  # Point this at your Render backend
  BACKEND_URL = "https://snakesnape.netlify.app/"
